using Eskineria.Core.Shared.Localization;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;


namespace Eskineria.WebApi.Configuration;

public static class OpenApiConfiguration
{
    public static OpenApiOptions AddEskineriaOpenApi(this OpenApiOptions options)
    {
        options.AddSchemaTransformer((schema, context, cancellationToken) =>
        {
            if (context.JsonTypeInfo.Type == typeof(LocalizedContent))
            {
                schema.Description = "Localized content map. You can add any culture code, but 'en-US' and 'tr-TR' are standard.";
                schema.Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["en-US"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "English (US)" },
                    ["tr-TR"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "Turkish (TR)" }
                };
                schema.AdditionalPropertiesAllowed = true;
                schema.AdditionalProperties = new OpenApiSchema
                {
                    Type = JsonSchemaType.String,
                    Description = "Any other culture code, e.g. de-DE, fr-FR."
                };
            }
            return Task.CompletedTask;
        });

        options.AddDocumentTransformer((document, context, cancellationToken) =>
        {
            document.Info.Title = "Eskineria App API";
            document.Info.Version = "v1";
            document.Info.Description = "Eskineria App API with Authentication. \n\n" +
                                       "This API supports the following features:\n" +
                                       "- **Authentication**: JWT Bearer Token\n" +
                                       "- **Localization**: Multi-language support";

            document.Info.Contact = new OpenApiContact
            {
                Name = "Eskineria Support",
                Email = "support@eskineria.com",
                Url = new Uri("https://eskineria.com/support")
            };

            document.Info.License = new OpenApiLicense
            {
                Name = "MIT License",
                Url = new Uri("https://opensource.org/licenses/MIT")
            };

            document.Info.TermsOfService = new Uri("https://eskineria.com/terms");

            /*
            document.Servers = new List<OpenApiServer>
            {
                new() { Url = "http://localhost:5285", Description = "Local Development" } 
            };
            */
            
            var securityScheme = new OpenApiSecurityScheme
            {
                Type = SecuritySchemeType.Http,
                Scheme = "bearer",
                BearerFormat = "JWT",
                Description = "JWT Authorization header using the Bearer scheme."
            };

            document.Components ??= new OpenApiComponents();
            document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
            document.Components.SecuritySchemes.Add("Bearer", securityScheme);

            return Task.CompletedTask;
        });

        options.AddOperationTransformer((operation, context, cancellationToken) =>
        {
            // Add Accept-Language Header
            operation.Parameters ??= new List<IOpenApiParameter>();
            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "Accept-Language",
                In = ParameterLocation.Header,
                Description = "Language preference for the response (e.g., en-US, tr-TR).",
                Required = false,
                Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.String
                }
            });

            // Standard Error Schema (RFC 7807 Problem Details)
            var problemDetailsSchema = new OpenApiSchema
            {
                Type = JsonSchemaType.Object,
                Properties = new Dictionary<string, IOpenApiSchema>
                {
                    ["type"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A URI reference that identifies the problem type." },
                    ["title"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A short, human-readable summary of the problem type." },
                    ["status"] = new OpenApiSchema { Type = JsonSchemaType.Integer, Description = "The HTTP status code generated by the origin server for this occurrence of the problem." },
                    ["detail"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A human-readable explanation specific to this occurrence of the problem." },
                    ["instance"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A URI reference that identifies the specific occurrence of the problem." },
                    ["traceId"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "Unique identifier for the request trace." },
                    ["errorCode"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "Application specific error code." },
                    ["errors"] = new OpenApiSchema 
                    { 
                        Type = JsonSchemaType.Object, 
                        Description = "Validation errors where key is field name and value is array of errors.",
                        AdditionalProperties = new OpenApiSchema 
                        { 
                            Type = JsonSchemaType.Array,
                            Items = new OpenApiSchema { Type = JsonSchemaType.String }
                        }
                    }
                }
            };

            var createErrorResponse = (string description) => new OpenApiResponse 
            { 
                Description = description,
                Content = new Dictionary<string, OpenApiMediaType>
                {
                    ["application/problem+json"] = new OpenApiMediaType
                    {
                        Schema = problemDetailsSchema
                    }
                }
            };
            
            if (operation.Responses != null && !operation.Responses.ContainsKey("400"))
            {
                operation.Responses.Add("400", createErrorResponse("Bad Request - Invalid input or validation error."));
            }
            if (operation.Responses != null && !operation.Responses.ContainsKey("401"))
            {
                operation.Responses.Add("401", createErrorResponse("Unauthorized - Authentication token is missing or invalid."));
            }
            if (operation.Responses != null && !operation.Responses.ContainsKey("403"))
            {
                operation.Responses.Add("403", createErrorResponse("Forbidden - User does not have permission."));
            }
            if (operation.Responses != null && !operation.Responses.ContainsKey("500"))
            {
                operation.Responses.Add("500", createErrorResponse("Internal Server Error - An unexpected error occurred."));
            }

            if (operation.Responses != null && !operation.Responses.ContainsKey("200"))
            {
                var successSchema = new OpenApiSchema
                {
                    Type = JsonSchemaType.Object,
                    Properties = new Dictionary<string, IOpenApiSchema>
                    {
                        ["success"] = new OpenApiSchema { Type = JsonSchemaType.Boolean, Description = "Indicates if the request was successful." },
                        ["message"] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "Result message." },
                        ["statusCode"] = new OpenApiSchema { Type = JsonSchemaType.Integer, Description = "HTTP Status Code." },
                        ["data"] = new OpenApiSchema { Type = JsonSchemaType.Object, Description = "Response Data" }
                    }
                };

                operation.Responses.Add("200", new OpenApiResponse 
                { 
                    Description = "Success",
                    Content = new Dictionary<string, OpenApiMediaType>
                    {
                        ["application/json"] = new OpenApiMediaType
                        {
                            Schema = successSchema
                        }
                    }
                });
            }

            return Task.CompletedTask;
        });

        return options;
    }
}
